/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CategoryChart: typeof import('./src/components/CategoryChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Mobilite: typeof import('./src/components/Mobilite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
